server.port=8082

application-title=Auth Service
application-description=Auth Service API
application-version=1.0
application-license=MIT

spring.application.name=auth-service
spring.config.import=optional:configserver:http://localhost:8888/

eureka.instance.instance-id=${spring.application.name}:${server.port}
