server.port=8083

spring.application.name=user-service

application-title=User Service

spring.config.import=optional:configserver:http://localhost:8888/

eureka.instance.instance-id=${spring.application.name}:${server.port}